name: Windows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install Packages
      run: |
        pip install meson ninja

    - name: Build
      run: |
        meson setup --backend=ninja build -Dlog=true -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtools="all"
        where link
        ninja -C build install

    - uses: actions/upload-artifact@v4
      with:
        name: result_windows
        path: build/src/thorvg*

  static_loaders:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install Packages
      run: |
        pip install meson ninja

    - name: Build
      run: |
        meson setup --backend=ninja build -Dlog=true -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtools="all" -Dstatic=true
        where link
        ninja -C build install

    - uses: actions/upload-artifact@v4
      with:
        name: result_windows_static
        path: build/src/thorvg*

  unit_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Install Packages
      run: |
        pip install meson ninja

    - name: Build
      run: |
        meson setup --backend=ninja build -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtests=true --errorlogs
        where link
        ninja -C build install test

    - uses: actions/upload-artifact@v4
      with:
        name: UnitTestReport
        path: build/meson-logs/testlog.txt

